services:
  zookeeper-service:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka-service:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "resource_model_topic:1:3"

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - 3306:3306
    restart: always

  resource-service:
    build: ResourceService
    environment:
      - JDBC_URL=jdbc:mysql://mysql-db:3306/resource-db?serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    ports:
      - 8080:8080
    volumes:
      - upload:/upload
    depends_on:
      - mysql-db

  song-service:
    build: SongService
    environment:
      - JDBC_URL=jdbc:mysql://mysql-db:3306/resource-db?serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    ports:
      - 8081:8081
    depends_on:
      - mysql-db

  resource-processor:
    build: ResourceProcessor
    ports:
      - 8082:8082
    volumes:
      - upload:/upload
    depends_on:
      - mysql-db

volumes:
  upload:
    external: true