server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: resource-service
  datasource:
    url: ${JDBC_URL:jdbc:mysql://mysql-db:3306/resource-db?serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect