server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: resource-processor
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
song:
  service:
    base:
      url: http://song-service:8081/api/songs/