server:
  port: 8082
  servlet:
    context-path: /api

spring:
  kafka:
    consumer:
#      properties:
#        spring:
#          deserializer:
#            value:
#              delegate:
#                class: org.springframework.kafka.support.serializer.JsonDeserializer
#          json:
#            trusted:
#              packages: com.epam.microservice.resourceservice.model.ResourceModel
      bootstrap-servers: kafka:9092
      group-id: "resource_group"
      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
  application:
    name: resource-processor
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
song:
  service:
    base:
      url: http://song-service:8081/api/songs/